# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestsuites1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test(self):
        self.driver.get("https://ceshiren.com/")
        self.driver.set_window_size(1292, 1400)
        self.driver.find_element(By.CSS_SELECTOR, ".d-button-label").click()
        self.driver.close()

    def test_testclick(self):
        self.driver.get("https://ceshiren.com/")
        time.sleep(2)
        self.driver.set_window_size(1292, 1400)
        time.sleep(2)
        self.driver.find_element(By.CSS_SELECTOR, "#ember97 .category-name").click()
        time.sleep(2)
        # self.driver.find_element(By.CSS_SELECTOR, "#create-topic > span").click()
        # time.sleep(2)
        self.driver.close()
